--liquibase formatted sql
--changeset shoppinglist_sql:initial_db

CREATE TABLE IF NOT EXISTS users
(
    id bigint NOT NULL PRIMARY KEY,
    username varchar(100) NOT NULL,
    chat_phase varchar(10)
);

CREATE TABLE IF NOT EXISTS shopping_lists
(
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id bigint UNIQUE NOT NULL,
    CONSTRAINT fk_shopping_lists_to_user FOREIGN KEY(user_id) REFERENCES users(id)
);

CREATE TABLE IF NOT EXISTS products
(
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    product_name varchar(100) NOT NULL,
    shopping_list_id bigint NOT NULL,
    CONSTRAINT fk_products_to_shopping_lists FOREIGN KEY(shopping_list_id) REFERENCES shopping_lists(id)
);
